### ISSUE TITLE
Checklist: Add more missing items

### ISSUE THREAD

**Issue by onox** [Juanvvc/c172p-detailed#4]
Some missing items could be added to the checklists:

To "Before Starting Engine":

1. [x] "Avionics Power Switch": Add a binding action to turn it off

2. [x] "Fuel Quantity", "CHECK"

To page 2 of "Before Takeoff":

1. [x] "Transponder Mode", "SBY OR ALT" (Remove from "Normal Takeoff" and "Short Field Takeoff" checklists)

2. [x] "Landing Light", "AS REQUIRED"

To "Cruise":

1. [x] "Altimeter", "SET"

2. [x] "Fuel Quantity", "CHECK"

3. [x] "Lights", "AS REQUIRED"

To "Descent":

1. [x] "ATIS", "NOTED"

2. [x] "Altimeter", "SET QNH"

3. [x] "Landing Light", "ON"

4. [x] "Fuel Quantity", "CHECK"

To "After Landing":

1. [x] "Transponder", "SBY"

2. [x] "Landing Light", "AS REQUIRED"

3. [x] "Taxi Light", "ON"

To "Securing Airplane":

1. [x] "Power", "SET 1000 RPM"

2. [x] Change "Avionics, Power, Electrical, Autopilot" to "Electrical Consumers", "ALL OFF" (Which switches should I check exactly?)

3. [x] "Avionics", "OFF"

4. [x] Fix marker location of "Ignition Switch"

5. [x] "Flashing Beacon", "OFF"

6. [x] "Master Switch", "OFF"

7. [x] "Parking Brake", "SET AS CONVENIENT"

**Comment by onox** [comment]
"Starting Engine" checklist contains "Master Switch" and "ALT Switch". Shouldn't this be moved to "Before Starting Engine" checklist as "Master Switch And Alternator"?

**Comment by gilbertohasnofb** [comment]
Some checklists have it "Before Starting Engine", others "Starting Engine". I think we should follow a single source on this (if you want, we can use that pdf I posted the link before).

But I think there is a terminology problem here: master switch refers to BOTH battery and alternator switches. On that pdf, it is written as "Battery master & alternator", but the most common term I've seen in checklist (I checked some 6 different ones) is simply "Master switch ON", thus referring to both ALT and BAT.

**Comment by onox** [comment]
Shall I name it "Master Switch" (referring to ALT and BAT) and move it to "Before Starting Engine" checklist?

**Comment by gilbertohasnofb** [comment]
I think you should name it Master Switch only. As for the placement, I guess that is fine (different checklists have it in different places). In the end it doesn't matter that much to be honest, but we can follow a single checklist as reference. In that case, if you want to use that pdf I posted before as reference, that could be good.

Also, are there emergency procedures in our current checklist? If not, I can help finding what they are.

**Comment by Juanvvc** [comment]
Battery runs out very fast, so you want the master ON as less time as possible if the engine is not running. Also, sections are just "logical sections" and not normative, so it is not really something important if MASTER ON is in "before starting engine" or in "starting engine". The most important thing is that it MASTER ON must be done only seconds before starting the engine. Not minutes. Seconds. This is easy when the checklist is writen on a paper. In the specific case of FlightGear, since "moving to the next checklist" involves moving the mouse and pressing a button to change a window, I'd say "MASTER ON" must be in the same list than "STARTER ON" to hint the virtual pilot to go through this procedure as fast as possible. Usability. There is no reference to the beacon in the official Cessna checklists, but I agree switching the Beacon ON is a very common practice just after MASTER ON. Regarding the alternator, this is something funny: on most propeller aircrafts, the alternator is swithed ON after the engine starts running, not before (there is not any alternator to use if the engine is not running). On the C172, checklists say the alternator can be switched on at the same time than the battery. I don't know why. I'd say, as gilberto suggests: just pick up a checklist and copy it. Current checklist is based on the official 1982 C172N, except the alternator.

**Comment by gilbertohasnofb** [comment]
Totally agree with what you wrote, Juan. Also, just as a side note, some checklists even write that the beacon should be on BEFORE the master switch is turned on (probably to limit the amount of steps from the battery being on until the starter).

**Comment by Juanvvc** [comment]
Some pilots recommend beacon always ON and never switch it OFF. This way, you can see if you forgot to switch the master OFF after hangaring the aircraft :)

**Comment by gilbertohasnofb** [comment]
That makes complete sense to me!

**Comment by onox** [comment]
I have removed "Flashing Beacon" in the "Securing Airplane" checklist in the first comment.

Should I add "ATIS" to some checklist? "Before Starting Engine"?

**Comment by gilbertohasnofb** [comment]
I have seen "ATIS check" while still on ground only in some checklists, but most of them only have ATIS check during the "Descent check". I think it doesn't make sense to add it to "Before Starting Engine" because you would need the battery in order to turn the avionics and radios on, and that is not recommended for the reasons Juan described above. The few times I have seen ATIS check while on ground, it was in some section such as "Before Taxing" or "Check After Engine Start" or something like this, but certainly after the engine was running. 

That said, and as I previously wrote in the forum, I have the staggering amount of 1 single hour in a Cessna 152 under my belt, so all I know is from reading stuff on the internet.

**Comment by Juanvvc** [comment]
Not switching it OFF is a deviation of the checklist SOMETIMES recommended by the operator. For good reasons, that's true. The last word about a checklist is said by the pilot, the next to last by the operator of the aircraft and the next by the maker. I strongly believe the checklist must say BEACON OFF when securing the aircraft, but it is the pilot or the operator who decides. Should we save the state of the switches when FlightGear ends? Probably.

The ATIS in the checklist makes no sense. I have landed or taken off from more than 20 different airports. Only one of them had ATIS (Ibiza) and I forgot to check it! Most airports normally operated by a C172 won't have ATIS. Most of them won't even be in controlled airspaces. There are some procedures than cannot be in the checklist. At some airports, you have to request clearance before starting the engine. At others, you can start the engine at any moment but you must get clearance for taxiing. Finally, at other airports, starting the engine and taxiing is under your sole responsibility. Clearances, radio communications and any other procedure specific to an airport cannot be in the checklist. You are assumed to follow them because you read and have the airport charts with you, right?

**Comment by onox** [comment]
Okay, should I add "Flashing Beacon" with "OFF" as yellow/green or grey?

**Comment by Juanvvc** [comment]
I prefer yellow/green, if possible :)

**Comment by onox** [comment]
What about the "Landing Light", "OFF" or "AS REQUIRED" (What do you prefer?) in "After Landing"?

**Comment by Juanvvc** [comment]
Flaps UP just after landing. Landing Light as required after clearing the holding position of the runway. It will be OFF during the day and ON if there is low visibility (under VMC or at night) Transponder should be set to Standby after clearing the holding position of the runway. If there is a taxi light (I cannot remember if our C172 has a taxi light), switch it ON, probably instead of the landing light unless you really benefit from the extra light.

"Electrical consumers" is ok for an experienced pilot, but I think newbies will prefer a list of the avionics they have to switch off. In any case, as discussed in the forum, this is sometimes a recommendation of the operator. If there is an avionics switch (and we implemented this switch), then you don't need to switch all avionics off, only the avionics switch. In fact, we started saving the state of the avionics after this discussion in the forum.

I prefer  "Avionics, Power, Electrical, Autopilot ALL OFF", but as you can see, there are other opinions :) Just check for the state of the avionics switch.

**Comment by gilbertohasnofb** [comment]
> I cannot remember if our C172 has a taxi light

I am sure it has a switch for taxi light.
